-- MySQL Script generated by MySQL Workbench
-- 10/28/16 12:18:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kyundb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kyundb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kyundb` DEFAULT CHARACTER SET utf8 ;
USE `kyundb` ;

-- -----------------------------------------------------
-- Table `kyundb`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kyundb`.`car` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `manufacturer` VARCHAR(45) NOT NULL,
  `production_year` YEAR NOT NULL,
  `class` VARCHAR(45) NOT NULL,
  `body_style` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) UNSIGNED NOT NULL,
  `amount_left` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kyundb`.`car_photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kyundb`.`car_photo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `photo` BLOB NOT NULL,
  `description` VARCHAR(45) NULL,
  `car_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_car_photo_car1_idx` (`car_id` ASC),
  CONSTRAINT `fk_car_photo_car1`
    FOREIGN KEY (`car_id`)
    REFERENCES `kyundb`.`car` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kyundb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kyundb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kyundb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kyundb`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cast` DECIMAL(12,2) UNSIGNED NOT NULL,
  `date` DATE NOT NULL,
  `fk_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_user_idx` (`fk_user` ASC),
  CONSTRAINT `fk_user_order`
    FOREIGN KEY (`fk_user`)
    REFERENCES `kyundb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kyundb`.`car_in_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kyundb`.`car_in_order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT UNSIGNED NOT NULL,
  `fk_car` INT NOT NULL,
  `fk_order` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_car_idx` (`fk_car` ASC),
  INDEX `fk_order_idx` (`fk_order` ASC),
  CONSTRAINT `fk_car`
    FOREIGN KEY (`fk_car`)
    REFERENCES `kyundb`.`car` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order`
    FOREIGN KEY (`fk_order`)
    REFERENCES `kyundb`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kyundb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kyundb`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `is_admin` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kyundb`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kyundb`.`user_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_user` INT NOT NULL,
  `fk_role` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_user_idx` (`fk_user` ASC),
  INDEX `fk_role_idx` (`fk_role` ASC),
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`fk_user`)
    REFERENCES `kyundb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_user`
    FOREIGN KEY (`fk_role`)
    REFERENCES `kyundb`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
